### ISSUE TITLE
Saturday Catering

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#104]
Andrew Riley, Andrew Riley, Andrew Riley... Hrmm... That seemed to work last year, wonder if it works this time? ;)

GRINGOSSSSS
Some quick notes from last year:
- Plan for 250, adjust a week out - Attendance was about 210
- Saturday catering only
- FTC opens at 7:30am
- They have vegan and gluten-free options available.

**Comment by andrewmriley** [comment]
I should probably update this. Waiting to hear back from Gringos.

**Comment by andrewmriley** [comment]
Spoke with Phil at Gringos. He's going to send over the initial paperwork with estimates. He did say since he knows this is an anniversary year that they can do some special catering stuff. We talked about possibly doing a hot item for breakfast and possibly something special at snack time.  Any ideas for this would be appreciated.

I also owe Phil a copy of the schedule (when registration starts, lunch time, snack time etc) before the day of the event so they know their setup times.

**Comment by andrewmriley** [comment]
@Ky1e @ultimike  I've got the estimated invoice but it has personally identifying info for me and Gringos so I'd rather not doxx us. Who should I email it to?

**Comment by ultimike** [comment]
Send it to me, but cc Don (if you have his email address - if not, not
worries, I'll forward it).

One other thing - at this point, we're estimating 240 attendees on
Saturday.

thanks,
-mike
