### ISSUE TITLE
Accordion (or something else) for "Event Blocks on Event (eblo)"

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#129]
Greg,

I'm not sure if this is something that we need Claudio's input on, but I know that @jeppy64 and I talked about the various blocks in the "Event Blocks on Event (eblo)" being collapsible, as we're likely to have a few of those, each with more than a paragraph or so of content in each. 

We want to make sure the page doesn't end up being 6 miles tall, so the thought was to have all these blocks in some sort of collapsible "thing". An accordion comes to mind, but I'm cool with anything that save vertical space. 

thanks,  
-mike

**Comment by jeppy64** [comment]
Hey Guys,

In the codebase is the old workhorse module Collapse Text. So we can easily wrap block content in collapse my text here /collapsed

Here's the module: https://www.drupal.org/project/collapse_text

**Comment by grshane** [comment]
I added the collapsible sections. Waiting on Claudio to get me some better ideas on the UX. Suggestions welcome.

**Comment by modulist** [comment]
subscribing...

**Comment by modulist** [comment]
I don't think the accordion or collapsible sections work well at all. I think we've reached a limit to how much content we want to put on a single home page, and that much of this would be more easily found on an **About** page or a **Speakers** page. That's what I had envisioned when I proposed having the info icon in the proposed menu.

![top menu - mobile](https://user-images.githubusercontent.com/713327/33780078-60907fe8-dc1d-11e7-90b4-c8ca340ffc76.png)

That said, I feel that the **Lodging** and **After Party** content would be best served by being on the **About** page. 

The Information for Presenters content should be in a block on the **Speakers** page. Eventually, we can add any speaker bios we have to that page as well.

@grshane and I discussed having a **Legal** page that's linked to from the footer, which would contain the Code of Conduct, Privacy, and other legal content. If the Code of Conduct needs to be more prominent, we could have it appear in a modal dialog box when the user clicks on the **Register Now** button, much like a EULA popup.

I'm also struggling to find a place for the latest tweets that are now at the bottom of the homepage. I think they should track the #fldrupal2018 hashtag instead of the @fldrupalcamp account so that the content is better targeted to this conference. I'm open to anyone else's idea on how to handle this.
