### ISSUE TITLE
Sponsor Email - ZipSprout

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#63]
Not sure if this is spam.

````
Hi,

I'm Jasmine from ZipSprout.com. We match our business clients with local
organizations like yours, and you can sign up for free. Is there a PDF or
list of cost and benefits you can share?

You can respond to this email, or learn more about ZipSprout by visiting our
website: https://zipsprout.com/sponsorships-for-organizations/

Best,

Jasmine George | Matchmaker | Zipsprout.com | (919) 907-1993
````

**Comment by ultimike** [comment]
I responded.

**Comment by mahannay** [comment]
I'm the CEO of ZipSprout. We're not spam :). We find local sponsorship opportunities at scale for our clients (businesses). To do this, we reach out to local organizations across the US to find out how to sponsor them, then select opportunities that fit our clients' budget and brand. We don't charge local organizations or nonprofits. We charge our clients - the businesses - per opportunity we secure for them, since we're essentially handling a local marketing campaign end-to-end. I hope you were able to find out what you needed from Jasmine, but feel free to email me (hello@zipsprout.com) if you have more questions. 

Megan

**Comment by ultimike** [comment]
Megan - can we set up a time to talk so that I can get a better understanding of what you're offering?

thanks,  
-mike

**Comment by mherchel** [comment]
Closing
